services:
  planner-api:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --reload-dir /app --host 0.0.0.0 --port 8000
    depends_on:
      - mongo
    environment:
      - PYTHONUNBUFFERED=1

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
